# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: cmd/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
        - goos: darwin
          goarch: 386

archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows

    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    tap:
      owner: sethkor
      name: homebrew-tap
    folder: Formula
    description: "Fast S3 Tools built in GoLang Using Multiparts and Concurrency"
    test: |
      system "#{bin}/program --version"


